# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-07 01:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=50)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('event_date', models.DateTimeField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Event_Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_1', models.CharField(max_length=128, verbose_name='address')),
                ('address_2', models.CharField(blank=True, max_length=128, verbose_name="address cont'd")),
                ('city', models.CharField(default='Oklahoma City', max_length=64, verbose_name='city')),
                ('state', models.CharField(default='OK', max_length=2, verbose_name='state')),
                ('zip_code', models.CharField(default='73142', max_length=5, verbose_name='zip code')),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.Event_Address'),
        ),
    ]
