# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-07 02:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event_address',
            name='description',
            field=models.CharField(default='Test', max_length=128, verbose_name='description'),
            preserve_default=False,
        ),
    ]
