# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-09 01:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_event_address_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='event_address',
            name='google_maps',
            field=models.URLField(default='https://www.google.com/maps/place/12505+Eric+Field+Pl,+Oklahoma+City,+OK+73142/@35.4826479,-97.4791974,10z/data=!4m5!3m4!1s0x87b2035cc60b8f0d:0x3dd7541e3217754e!8m2!3d35.596675!4d-97.629365', verbose_name='goolge maps'),
            preserve_default=False,
        ),
    ]
