# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-09 15:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0004_eventbeer'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EventBeer',
            new_name='Event_Beer',
        ),
    ]
