# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-10-04 19:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0008_auto_20171004_1136'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='description',
            field=models.TextField(default='Test Description', max_length=1000),
            preserve_default=False,
        ),
    ]
