# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-10-11 14:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0020_remove_club_user_is_pending'),
        ('event', '0012_auto_20171011_0928'),
    ]

    operations = [
        migrations.AddField(
            model_name='event_address',
            name='club',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='club.Club'),
            preserve_default=False,
        ),
    ]
