# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-01-17 21:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0015_auto_20180108_0855'),
    ]

    operations = [
        migrations.AddField(
            model_name='event_beer',
            name='brewery_id',
            field=models.CharField(default='ZZZZZ', max_length=20),
            preserve_default=False,
        ),
    ]
