# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-03-05 22:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Beer_Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category_bdb_id', models.CharField(max_length=5)),
                ('create_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
