# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-03-07 16:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apidata', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Beer_Style',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('style_bdb_id', models.CharField(max_length=5)),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=1500)),
                ('ibuMin', models.CharField(blank=True, max_length=20)),
                ('ibuMax', models.CharField(blank=True, max_length=20)),
                ('abvMin', models.CharField(blank=True, max_length=20)),
                ('abvMax', models.CharField(blank=True, max_length=20)),
                ('srmMin', models.CharField(blank=True, max_length=20)),
                ('srmMax', models.CharField(blank=True, max_length=20)),
                ('ogMin', models.CharField(blank=True, max_length=20)),
                ('ogMax', models.CharField(blank=True, max_length=20)),
                ('fgMin', models.CharField(blank=True, max_length=20)),
                ('fgMax', models.CharField(blank=True, max_length=20)),
                ('create_date', models.DateTimeField(blank=True, null=True)),
                ('update_date', models.DateTimeField(blank=True, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apidata.Beer_Category')),
            ],
        ),
    ]
