# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-31 03:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='beer_category',
            name='alcohol_content',
            field=models.CharField(default='test', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='beer_category',
            name='description',
            field=models.CharField(max_length=1000),
        ),
    ]
