# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-02 00:25
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0002_auto_20170530_2215'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wanted_Beers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beer_company', models.CharField(max_length=100)),
                ('beer_name', models.CharField(max_length=500)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('bdb_id', models.CharField(max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='beer_category',
            name='alcohol_content',
        ),
        migrations.AddField(
            model_name='favorite_beers',
            name='bdb_id',
            field=models.CharField(default='xxxxx', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wanted_beers',
            name='beer_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.Beer_Category'),
        ),
        migrations.AddField(
            model_name='wanted_beers',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
