# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-04 04:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20170601_1925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorite_beers',
            name='beer_category',
            field=models.CharField(default='Lager', max_length=100),
            preserve_default=False,
        ),
    ]
