# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-25 03:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_beer_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='beer_rating',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
