# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-25 14:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_beer_rating_date_added'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='beer_rating',
            name='user',
        ),
        migrations.AddField(
            model_name='beer_rating',
            name='beer_category',
            field=models.CharField(default='temp', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='beer_rating',
            name='beer_company',
            field=models.CharField(default='temp', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='beer_rating',
            name='beer_name',
            field=models.CharField(default='temp', max_length=500),
            preserve_default=False,
        ),
    ]
