# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-26 02:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_beer_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='beer_banner',
            name='beer_website',
            field=models.URLField(default='', max_length=250),
            preserve_default=False,
        ),
    ]
