# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-24 03:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_auto_20170720_1757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beer_note',
            name='note',
            field=models.TextField(max_length=1000),
        ),
    ]
