# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-27 19:33
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0013_auto_20170823_2208'),
    ]

    operations = [
        migrations.CreateModel(
            name='Beer_Color',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bdb_id', models.CharField(max_length=20)),
                ('persistent', models.BooleanField(default=False)),
                ('rocky', models.BooleanField(default=False)),
                ('large', models.BooleanField(default=False)),
                ('fluffy', models.BooleanField(default=False)),
                ('dissipating', models.BooleanField(default=False)),
                ('lingering', models.BooleanField(default=False)),
                ('white', models.BooleanField(default=False)),
                ('offwhite', models.BooleanField(default=False)),
                ('tan', models.BooleanField(default=False)),
                ('frothy', models.BooleanField(default=False)),
                ('delicate', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
