# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-26 03:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_auto_20170903_2029'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='beer_attribute',
            options={'ordering': ['attribute']},
        ),
        migrations.AlterModelOptions(
            name='favorite_beers',
            options={'ordering': ['beer_name']},
        ),
        migrations.AlterModelOptions(
            name='wanted_beers',
            options={'ordering': ['beer_name']},
        ),
    ]
