# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-28 16:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_auto_20170925_2249'),
    ]

    operations = [
        migrations.AddField(
            model_name='beer_attribute_category',
            name='page_order',
            field=models.IntegerField(default=0),
        ),
    ]
