# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-11-19 19:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_auto_20171119_1318'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='beer_color',
            name='user',
        ),
        migrations.DeleteModel(
            name='Beer_Color',
        ),
    ]
