# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-11-20 02:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_beer_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='beer_score',
            name='beer_category',
            field=models.CharField(default='TEST', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='beer_score',
            name='beer_company',
            field=models.CharField(default='TEST', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='beer_score',
            name='beer_name',
            field=models.CharField(default='TEST', max_length=500),
            preserve_default=False,
        ),
    ]
