# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-01-11 21:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_auto_20171119_2021'),
    ]

    operations = [
        migrations.AddField(
            model_name='favorite_beers',
            name='brewery_id',
            field=models.CharField(default='ZZZZZ', max_length=20),
            preserve_default=False,
        ),
    ]
