# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-01-11 22:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0024_favorite_beers_brewery_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='beer_note',
            name='brewery_id',
            field=models.CharField(default='ZZZZZ', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='beer_score',
            name='brewery_id',
            field=models.CharField(default='ZZZZZ', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wanted_beers',
            name='brewery_id',
            field=models.CharField(default='ZZZZZ', max_length=20),
            preserve_default=False,
        ),
    ]
