# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-01-22 19:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0027_brewery_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='beer_score',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
