# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-01-22 22:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0028_beer_score_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='brewery_score',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
