# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-01-25 15:50
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0029_brewery_score_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='beer_score',
            name='score_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
