# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-01-25 16:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0030_beer_score_score_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beer_score',
            name='score_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
