# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-01-25 16:22
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0031_auto_20180125_1006'),
    ]

    operations = [
        migrations.AddField(
            model_name='brewery_score',
            name='score_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
