# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-02-04 02:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0033_auto_20180125_1022'),
    ]

    operations = [
        migrations.CreateModel(
            name='Beer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bdb_id', models.CharField(max_length=20)),
                ('beer_company', models.CharField(max_length=100)),
                ('beer_name', models.CharField(max_length=500)),
                ('beer_category', models.CharField(max_length=100)),
                ('brewery_id', models.CharField(max_length=20)),
                ('beer_image_url', models.URLField(max_length=250)),
                ('beer_website', models.URLField(max_length=250)),
                ('api_update_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
