# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-02-04 02:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0034_beer'),
    ]

    operations = [
        migrations.AddField(
            model_name='beer',
            name='beer_style',
            field=models.CharField(default='TEST', max_length=100),
            preserve_default=False,
        ),
    ]
