# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-02-04 02:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0036_remove_beer_beer_style'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='beer',
            name='beer_website',
        ),
    ]
