# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-02-04 03:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0038_auto_20180203_2059'),
    ]

    operations = [
        migrations.AddField(
            model_name='beer',
            name='brewery_image_url',
            field=models.URLField(blank=True, max_length=250),
        ),
    ]
