# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-02-12 17:11
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0039_beer_brewery_image_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Beer_User_Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beer_image', models.ImageField(upload_to='beer_image/')),
                ('description', models.CharField(blank=True, max_length=1000)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('beer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Beer')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
