# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-02-28 16:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0042_beer_user_image_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='beer_banner',
            name='bdb_id',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
    ]
