# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-03-01 20:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0043_beer_banner_bdb_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='beer_banner',
            name='beer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='home.Beer'),
        ),
    ]
