# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-03 01:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='club_admin',
            name='club',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='club.Club'),
            preserve_default=False,
        ),
    ]
