# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-16 19:38
from __future__ import unicode_literals

from django.db import migrations, models
import localflavor.us.models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0002_club_admin_club'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='city',
            field=models.CharField(default='Oklahoma City', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='club',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='club',
            name='state',
            field=localflavor.us.models.USStateField(blank=True, max_length=2, null=True),
        ),
    ]
