# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-19 20:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0005_club_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='club_user',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
