# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-26 03:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0006_club_user_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='Club_About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('established', models.DateField(auto_now_add=True)),
                ('is_public', models.BooleanField(default=True)),
                ('annual_fee', models.DecimalField(decimal_places=2, max_digits=6)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='club.Club')),
            ],
        ),
    ]
