# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-26 03:53
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0007_club_about'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club_about',
            name='established',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
