# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-26 04:00
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.utils.datetime_safe


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0008_auto_20170925_2253'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='club_about',
            name='club',
        ),
        migrations.AddField(
            model_name='club',
            name='annual_fee',
            field=models.DecimalField(decimal_places=2, default=0.00),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='club',
            name='established',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.DeleteModel(
            name='Club_About',
        ),
    ]
