# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-26 04:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0009_auto_20170925_2300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='annual_fee',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
