# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-27 04:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0010_auto_20170925_2305'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='club_announcement',
            options={'ordering': ['-date_added']},
        ),
        migrations.AddField(
            model_name='club',
            name='bio',
            field=models.CharField(default='Welcome to OK Beer Tasters!  This crowd is a group of friends in the Oklahoma City area.', max_length=1500),
            preserve_default=False,
        ),
    ]
