# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-29 02:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0013_auto_20170928_1411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club_announcement',
            name='expiration_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
