# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-10-02 19:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0014_auto_20170928_2150'),
    ]

    operations = [
        migrations.AddField(
            model_name='club_user',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
    ]
