# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-10-04 16:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0015_club_user_is_admin'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='club_user',
            options={'ordering': ['user__last_name']},
        ),
    ]
