# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-10-06 02:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0016_auto_20171004_1136'),
    ]

    operations = [
        migrations.AddField(
            model_name='club_user',
            name='is_pending',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='club_user',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
