# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-10-06 14:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0018_club_application'),
    ]

    operations = [
        migrations.RenameField(
            model_name='club_application',
            old_name='date_added',
            new_name='date_applied',
        ),
        migrations.AddField(
            model_name='club_application',
            name='date_completed',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
