# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-12-17 20:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0020_remove_club_user_is_pending'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='club',
            options={'ordering': ['state']},
        ),
        migrations.AddField(
            model_name='club',
            name='disp_members',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='club',
            name='display_member_vote',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
