# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-01-08 23:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0025_club_auto_approve'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='require_real_name',
            field=models.BooleanField(default=False),
        ),
    ]
